const blogSlugs: string[] = [
  'blog/best-shopify-welcome-email-apps-for-small-shopify-stores',
  'blog/best-shopify-abandoned-cart-apps-for-small-shopify-stores',
  'blog/best-shopify-post-purchase-email-apps-for-small-shopify-stores',
  'blog/best-shopify-win-back-email-apps-for-small-shopify-stores',
  'blog/best-shopify-product-launch-email-apps-for-small-shopify-stores',
  'blog/best-shopify-back-in-stock-email-apps-for-small-shopify-stores',
  'blog/best-shopify-review-request-apps-for-small-shopify-stores',
  'blog/best-shopify-vip-customer-email-apps-for-small-shopify-stores',
  'blog/best-shopify-replenishment-email-apps-for-small-shopify-stores',
  'blog/best-shopify-email-and-sms-marketing-apps-for-small-shopify-stores',
  'blog/best-shopify-welcome-email-apps-for-dtc-brands',
  'blog/best-shopify-abandoned-cart-apps-for-dtc-brands',
  'blog/best-shopify-post-purchase-email-apps-for-dtc-brands',
  'blog/best-shopify-win-back-email-apps-for-dtc-brands',
  'blog/best-shopify-product-launch-email-apps-for-dtc-brands',
  'blog/best-shopify-back-in-stock-email-apps-for-dtc-brands',
  'blog/best-shopify-review-request-apps-for-dtc-brands',
  'blog/best-shopify-vip-customer-email-apps-for-dtc-brands',
  'blog/best-shopify-replenishment-email-apps-for-dtc-brands',
  'blog/best-shopify-email-and-sms-marketing-apps-for-dtc-brands',
  'blog/best-shopify-welcome-email-apps-for-fashion-stores',
  'blog/best-shopify-abandoned-cart-apps-for-fashion-stores',
  'blog/best-shopify-post-purchase-email-apps-for-fashion-stores',
  'blog/best-shopify-win-back-email-apps-for-fashion-stores',
  'blog/best-shopify-product-launch-email-apps-for-fashion-stores',
  'blog/best-shopify-back-in-stock-email-apps-for-fashion-stores',
  'blog/best-shopify-review-request-apps-for-fashion-stores',
  'blog/best-shopify-vip-customer-email-apps-for-fashion-stores',
  'blog/best-shopify-replenishment-email-apps-for-fashion-stores',
  'blog/best-shopify-email-and-sms-marketing-apps-for-fashion-stores',
  'blog/best-shopify-welcome-email-apps-for-beauty-stores',
  'blog/best-shopify-abandoned-cart-apps-for-beauty-stores',
  'blog/best-shopify-post-purchase-email-apps-for-beauty-stores',
  'blog/best-shopify-win-back-email-apps-for-beauty-stores',
  'blog/best-shopify-product-launch-email-apps-for-beauty-stores',
  'blog/best-shopify-back-in-stock-email-apps-for-beauty-stores',
  'blog/best-shopify-review-request-apps-for-beauty-stores',
  'blog/best-shopify-vip-customer-email-apps-for-beauty-stores',
  'blog/best-shopify-replenishment-email-apps-for-beauty-stores',
  'blog/best-shopify-email-and-sms-marketing-apps-for-beauty-stores',
  'blog/best-shopify-welcome-email-apps-for-food-and-beverage-stores',
  'blog/best-shopify-abandoned-cart-apps-for-food-and-beverage-stores',
  'blog/best-shopify-post-purchase-email-apps-for-food-and-beverage-stores',
  'blog/best-shopify-win-back-email-apps-for-food-and-beverage-stores',
  'blog/best-shopify-product-launch-email-apps-for-food-and-beverage-stores',
  'blog/best-shopify-back-in-stock-email-apps-for-food-and-beverage-stores',
  'blog/best-shopify-review-request-apps-for-food-and-beverage-stores',
  'blog/best-shopify-vip-customer-email-apps-for-food-and-beverage-stores',
  'blog/best-shopify-replenishment-email-apps-for-food-and-beverage-stores',
  'blog/best-shopify-email-and-sms-marketing-apps-for-food-and-beverage-stores',
  'blog/best-shopify-welcome-email-apps-for-subscription-brands',
  'blog/best-shopify-abandoned-cart-apps-for-subscription-brands',
  'blog/best-shopify-post-purchase-email-apps-for-subscription-brands',
  'blog/best-shopify-win-back-email-apps-for-subscription-brands',
  'blog/best-shopify-product-launch-email-apps-for-subscription-brands',
  'blog/best-shopify-back-in-stock-email-apps-for-subscription-brands',
  'blog/best-shopify-review-request-apps-for-subscription-brands',
  'blog/best-shopify-vip-customer-email-apps-for-subscription-brands',
  'blog/best-shopify-replenishment-email-apps-for-subscription-brands',
  'blog/best-shopify-email-and-sms-marketing-apps-for-subscription-brands',
  'blog/best-shopify-welcome-email-apps-for-shopify-plus-merchants',
  'blog/best-shopify-abandoned-cart-apps-for-shopify-plus-merchants',
  'blog/best-shopify-post-purchase-email-apps-for-shopify-plus-merchants',
  'blog/best-shopify-win-back-email-apps-for-shopify-plus-merchants',
  'blog/best-shopify-product-launch-email-apps-for-shopify-plus-merchants',
  'blog/best-shopify-back-in-stock-email-apps-for-shopify-plus-merchants',
  'blog/best-shopify-review-request-apps-for-shopify-plus-merchants',
  'blog/best-shopify-vip-customer-email-apps-for-shopify-plus-merchants',
  'blog/best-shopify-replenishment-email-apps-for-shopify-plus-merchants',
  'blog/best-shopify-email-and-sms-marketing-apps-for-shopify-plus-merchants',
  'blog/best-shopify-welcome-email-apps-for-international-merchants',
  'blog/best-shopify-abandoned-cart-apps-for-international-merchants',
  'blog/best-shopify-post-purchase-email-apps-for-international-merchants',
  'blog/best-shopify-win-back-email-apps-for-international-merchants',
  'blog/best-shopify-product-launch-email-apps-for-international-merchants',
  'blog/best-shopify-back-in-stock-email-apps-for-international-merchants',
  'blog/best-shopify-review-request-apps-for-international-merchants',
  'blog/best-shopify-vip-customer-email-apps-for-international-merchants',
  'blog/best-shopify-replenishment-email-apps-for-international-merchants',
  'blog/best-shopify-email-and-sms-marketing-apps-for-international-merchants',
  'blog/best-shopify-welcome-email-apps-for-new-shopify-stores',
  'blog/best-shopify-abandoned-cart-apps-for-new-shopify-stores',
  'blog/best-shopify-post-purchase-email-apps-for-new-shopify-stores',
  'blog/best-shopify-win-back-email-apps-for-new-shopify-stores',
  'blog/best-shopify-product-launch-email-apps-for-new-shopify-stores',
  'blog/best-shopify-back-in-stock-email-apps-for-new-shopify-stores',
  'blog/best-shopify-review-request-apps-for-new-shopify-stores',
  'blog/best-shopify-vip-customer-email-apps-for-new-shopify-stores',
  'blog/best-shopify-replenishment-email-apps-for-new-shopify-stores',
  'blog/best-shopify-email-and-sms-marketing-apps-for-new-shopify-stores',
  'blog/best-shopify-welcome-email-apps-for-high-volume-stores',
  'blog/best-shopify-abandoned-cart-apps-for-high-volume-stores',
  'blog/best-shopify-post-purchase-email-apps-for-high-volume-stores',
  'blog/best-shopify-win-back-email-apps-for-high-volume-stores',
  'blog/best-shopify-product-launch-email-apps-for-high-volume-stores',
  'blog/best-shopify-back-in-stock-email-apps-for-high-volume-stores',
  'blog/best-shopify-review-request-apps-for-high-volume-stores',
  'blog/best-shopify-vip-customer-email-apps-for-high-volume-stores',
  'blog/best-shopify-replenishment-email-apps-for-high-volume-stores',
  'blog/best-shopify-email-and-sms-marketing-apps-for-high-volume-stores',
];

const modules = import.meta.glob('./**/*.astro', { eager: false });

export async function GET(): Promise<Response> {
  const site = 'https://www.shopifyemailmarketingtools.com';
  const paths = [
    ...Object.keys(modules)
      .filter((p) => !p.includes('/sitemap') && !p.includes('['))
      .map((p) => {
        let route = p.replace(/^\.\//, '/').replace(/\.astro$/, '');
        if (route.endsWith('/index')) route = route.slice(0, -'/index'.length);
        return route;
      }),
    ...blogSlugs.map((b) => `/${b}`),
  ].sort();
  const body =
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    paths.map((r) => `  <url><loc>${site}${r}</loc></url>`).join('\n') +
    `\n</urlset>`;
  return new Response(body, { headers: { 'Content-Type': 'application/xml' } });
}
